// base body actions
export const SET_BODY_SELECTION = 'SET_BODY_SELECTION';
export const RESET_BODY_SELECTION = 'RESET_BODY_SELECTION';

// restriction actions
export const UPDATE_RESTRICTION_SELECTION = 'UPDATE_RESTRICTION_SELECTION';

// manual actions
export const UPDATE_MANUAL_TYPE_SELECTION = 'UPDATE_MANUAL_TYPE_SELECTION';

// movement actions
export const UPDATE_MOVEMENT_SELECTION = 'UPDATE_MOVEMENT_SELECTION';

// therex purpose actions
export const UPDATE_THEREX_PURPOSE_SELECTION = 'UPDATE_THEREX_PURPOSE_SELECTION';

// cue actions
export const UPDATE_CUES_SELECTION = 'UPDATE_CUES_SELECTION';

// result actions
export const UPDATE_RESULTS_SELECTION = 'UPDATE_RESULTS_SELECTION';
