// base body actions
export const SET_BODY_SELECTION = 'SET_BODY_SELECTION';
export const RESET_BODY_SELECTION = 'RESET_BODY_SELECTION';

// restriction actions
export const UPDATE_RESTRICTION_SELECTION = 'UPDATE_RESTRICTION_SELECTION';

// manual actions
export const UPDATE_MANUAL_TYPE_SELECTION = 'UPDATE_MANUAL_TYPE_SELECTION';

// movement actions
export const UPDATE_MOVEMENT_SELECTION = 'UPDATE_MOVEMENT_SELECTION';
